image: Visual Studio 2017

version: '0.1.{build}'

configuration:
- Debug
- Release

platform: x86

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15

install:
    - call CI\appveyor\install.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%          # CMAKE_CONFIGURE_FLAGS and CMAKE_BUILD_FLAGS are defined in CI\appveyor\install.bat
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure